---
title: "Untitled"
author: "Kenji Macfarlane ID:26006480"
date: "22/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Testing with the first benchmark set.
```{r}
tr_test1 <- xgb.train(booster = "gbtree", objective = "binary:logistic", data = xgb_bm1[[1]], nrounds = 500, max_depth = 6, eval_metric = "logloss", n_estimators = 500, gamma = 0, alpha = 0)

pred_test1 <- predict(tr_test1, xgb_bm1[[2]])

for (i in 1:NROW(pred_test1)){
  if (pred_test1[i] > 0.6){
       pred_test1[i] = 1
     } else {
       pred_test1[i] = 0
     }
}

confusionMatrix(table(pred_test1, true_split1[[2]]$Signal))
```


1) Benchmark 1: $\tilde{t} = 1.2$ TeV and $\tilde{\chi}_1^0 = 600 $ GeV
```{r}
# Perform xgboost cv and extract minimum test MSE mean from each xgbcv
xgbcv_result1 <- perform_cv(new_param, xgb_bm1)

#### row/list number of the best xgbcv
best_xgbcv <- which.min(xgbcv_result1[,1])
best_param <- new_param[best_xgbcv,]

# train on partitioned set
tr_test1 <- xgb.train(params = best_param, data = xgb_bm1[[3]], nrounds =xgbcv_result1[best_xgbcv,2])
pred_test1 <- predict(tr_test1, xgb_bm1[[4]])

# Do a check to see what is a good cut-off
check <- part_split1[[2]] %>% mutate(Signal_pred = pred_test1, Signal = as.factor(Signal))
distribution(check, "Distribution of predicted events with $\\tilde{t} = 1.2$ TeV and $ \\chi_1^0 = 600 $ GeV - Preliminary")
check <- assign_label(check, 0.6)
confusionMatrix(table(check$Signal_pred, check$Signal))
rm(check)

# train on original training set
tr_xgb1 <- xgb.train(params = best_param, 
          data = xgb_bm1[[1]], nrounds = xgbcv_result1[best_xgbcv,2])

# test error after prediction
xgbpred1 <- predict(tr_xgb1, xgb_bm1[[2]])


check_data1 <- true_split1[[2]] %>% mutate(Signal_pred = xgbpred1, Signal = as.factor(Signal))
distribution(check_data1, "Distribution of predicted events with $\\tilde{t}=1.2$ TeV and $\\tilde{\\chi}_1^0=600$ GeV") # CANNOT RUN WHEN PLOTLY IS LOADED

# Create Confusion Matrix based on the best possible cut-off seen in the plot (roughly 100 Events or less with Backgrounds is good I think)
check_data1 <- assign_label(check_data1, 0.6)
confusionMatrix(table(check_data1$Signal_pred, check_data1$Signal))
# First was 0.920, then increased by 0.001 after a few tries testing the alpha ranges

# Get relevant values off the outcome
b1_vals <- Values(check_data1$Signal_pred, true_split1, Data_Benchmark01, 0.1593)
b1_vals
```


Visualisation using guided tours
```{r}
var1 <- true_split1[[2]] %>% mutate(Signal_pred = xgbpred1) %>% select("MissingET.MET", "MissingET.Phi", "Lepton.PT", "Lepton.Phi", "ScalarHT.HT", "Jet1.PT", "MissingET.Eta", "BJet.PT", "Signal", "Signal_pred") %>% sample_n(NROW(true_split1[[2]])/10)
var1 <- assign_label(var1, 0.6)

col_v1 <- group_color(var1)
var1[col_v1[,1]!=col_v1[,2],"Signal_pred"] <- if_else(col_v1[col_v1[,1]!=col_v1[,2],1]=="black", 2, 3)  
# False positive = Green/2 and False negative = red/3
write_csv(as.data.frame(var1), "/home/user1/Desktop/tourr variables/var1.csv")

# Rescale
var1 <- rescale(var1[,-9]) 

# Save tour history
seed <- .Random.seed
#.Random.seed <- seed
t1 <- save_history(var1[,-9], guided_tour(ashapetour(cl = col_v1[,3], alpha = 0.4, hull_var = c("black")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(var1[,-9], planned_tour(t1), col = col_v1[,3], fps = 50)
X11()

htmlwidgets::saveWidget(as_widget(create_animation(t1, "/home/user1/Desktop/tourr variables/var1.csv", var1)), "/home/user1/Desktop/Images for thesis/tourr/plotly animation/bm1.html")

# Save the tour plot
render(var1[,-9], planned_tour(t1), display_xy(col = col_v1[,3]), frames = 50, "png", "/home/user1/Desktop/Images for thesis/tourr/bm1/bm1_test-%03d.png")
# pdf version actually captures the whole path

# Reorder the data in increasing order (TN → TP → FP → FN) of Signal_pred variable 
# with order(as.data.frame(var1)$Signal_pred, decreasing = FALSE)
```

For the training set
```{r}
var1_tr <- true_split1[[1]] %>% select("MissingET.MET", "MissingET.Phi", "Lepton.PT", "Lepton.Phi", "ScalarHT.HT", "Jet1.PT", "MissingET.Eta", "BJet.PT", "Signal") %>% sample_n(NROW(true_split1[[1]])/10)

col_v1_tr <- if_else(var1_tr$Signal==0, "black", "blue")
write_csv(as.data.frame(var1_tr), "/home/user1/Desktop/tourr variables/var1_tr.csv")
# Rescale
var1_tr <- rescale(var1_tr[,-9]) 

# Use same tour history as the test set
X11()
animate_xy(var1_tr, planned_tour(t1_tr), col = col_v1_tr, fps = 50)
X11()

htmlwidgets::saveWidget(as_widget(create_animation_tr(t1_tr, "/home/user1/Desktop/tourr variables/var1_tr.csv", var1_tr)), "/home/user1/Desktop/Images for thesis/plotly animation/tourr/bm1_tr.html")

# Save the tour plot
render(var1_tr, planned_tour(t1_tr), display_xy(col = col_v1_tr), frames = 50, "png", "/home/user1/Desktop/Images for thesis/tourr/bm1/bm1_tr1-%03d.png")
# pdf version actually captures the whole path
```

Only the misclassified points
```{r}
false1 <- read_csv("/home/user1/Desktop/tourr variables/var1.csv")
false1 <- subset(false1, col_v1[,1]!=col_v1[,2])

col_f1 <- if_else(false1$Signal_pred=="2", "red", "blue") # blue is FN, red is FP
write_csv(as.data.frame(false1), "/home/user1/Desktop/tourr variables/false1.csv")
false1 <- rescale(select(false1, -"Signal"))

f1 <- save_history(false1[,-ncol(false1)], guided_tour(ashapetour(cl = col_f1, alpha = 0.4, hull_var = c("red")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(false1[,-ncol(false1)], planned_tour(f1), col = col_f1, fps = 50)
X11()

animation_FPFN(f1, "/home/user1/Desktop/tourr variables/false1.csv", false1)
```

Only for the signal points
```{r}
fntp1 <- read_csv("/home/user1/Desktop/tourr variables/var1.csv")
fntp1 <- subset(fntp1, fntp1[,"Signal"]=="1")
write_csv(as.data.frame(fntp1), "/home/user1/Desktop/tourr variables/fntp1.csv")
col_sig1 <- if_else(fntp1$Signal_pred=="3", "red", "blue") # blue is TP, red is FN
fntp1 <- rescale(select(fntp1, -"Signal"))

sig1 <- save_history(fntp1[,-ncol(fntp1)], guided_tour(ashapetour(cl = col_sig1, alpha = 0.4, hull_var = c("red")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(fntp1[,-ncol(fntp1)], planned_tour(sig1), col = col_sig1, fps = 50)
X11()

animation_signal(sig1, "/home/user1/Desktop/tourr variables/fntp1.csv", fntp1)
```

Only for the background points
```{r}
fptn1 <- read_csv("/home/user1/Desktop/tourr variables/var1.csv")
fptn1 <- subset(fptn1, fptn1[,"Signal"]=="0")
write_csv(as.data.frame(fptn1), "/home/user1/Desktop/tourr variables/fptn1.csv")
col_back1 <- if_else(fptn1$Signal_pred=="2", "red", "blue") # blue is TN, red is FP
fptn1 <- rescale(select(fptn1, -"Signal"))

back1 <- save_history(fptn1[,-ncol(fptn1)], guided_tour(ashapetour(cl = col_back1, alpha = 0.4, hull_var = c("blue")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(fptn1[,-ncol(fptn1)], planned_tour(back1), col = col_back1, fps = 50)
X11()

animation_background(back3, "/home/user1/Desktop/tourr variables/fptn1.csv", fptn1)
```

Create a gif
```{r}
all_dir <- list.dirs(path = "/home/user1/Desktop/Images for thesis/tourr/bm1/test", recursive = TRUE)
# change end of file according to the folder I want to create gifs with
for (d in all_dir){
  name <- paste0("/home/user1/Desktop/Images for thesis/tourr", "/bm1_test.gif") # change pasted name to match the run number
  fls <- list.files(d, full.names = TRUE)
  gifski(fls , name, loop = FALSE)
}
```
