---
title: "Untitled"
author: "Kenji Macfarlane ID:26006480"
date: "22/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Benchmark 4: $ \tilde{t}= 750 \text{GeV}, \chi_1^0 = 1 \text{GeV} $. 
```{r}
tr_test_I <- xgb.train(booster = "gbtree", objective = "binary:logistic", data = xgb_bm_I[[1]], nrounds = 500, max_depth = 6, eval_metric = "logloss", n_estimators = 500, gamma = 0, alpha = 0)
pred_test_I <- predict(tr_test_I, xgb_bm_I[[2]])
for (i in 1:NROW(pred_test_I)){
  if (pred_test_I[i] > 0.6){
       pred_test_I[i] = 1
     } else {
       pred_test_I[i] = 0
     }
}
      
confusionMatrix(table(pred_test_I, true_split_I[[2]]$Signal))
# Initial values below 90% - 0.89
```

```{r, message = False}
xgbcv_result_I <- perform_cv(new_param, xgb_bm_I)
# row/list number of the best xgbcv
best_xgbcv <- which.min(xgbcv_result_I[,1])
best_param <- new_param[best_xgbcv,]

# train on partitioned set
tr_test_I <- xgb.train(params = best_param, data = xgb_bm_I[[3]], nrounds = xgbcv_result_I[best_xgbcv,2])
pred_test_I <- predict(tr_test_I, xgb_bm_I[[4]])

# Do a check to see what is a good cut-off
check <- part_split_I[[2]] %>% mutate(Signal_pred = pred_test_I, Signal = as.factor(Signal))
distribution(check, "Distribution of predicted events with $\\tilde{t} = 750$ GeV and $\\tilde{\\chi} = 1 $ GeV - Preliminary")
check <- assign_label(check, 0.6)
confusionMatrix(table(check$Signal_pred, check$Signal)) # Showed 0.9494 accuracy
rm(check)

# train on original training set
tr_xgb_I <- xgb.train(params = best_param, 
          data = xgb_bm_I[[1]], nrounds = xgbcv_result_I[best_xgbcv,2])

# test error after prediction
xgbpred_I <- predict(tr_xgb_I, xgb_bm_I[[2]])

check_data_I <- true_split_I[[2]] %>% mutate(Signal_pred = xgbpred_I, Signal = as.factor(Signal))
distribution(check_data_I, "Distribution of predicted events with $\\tilde{t} = 750$ GeV and $\\tilde{\\chi}_1^0 = 1 $ GeV")

# Create Confusion Matrix based on the best possible cut-off seen in the plot (roughly 100 Events or less with Backgrounds is good I think)
check_data_I <- assign_label(check_data_I, 0.6)

confusionMatrix(table(check_data_I$Signal_pred, check_data_I$Signal)) # Showed an improvement to 0.9503

In_vals <- Values(check_data_I$Signal_pred, true_split_I, Data_Inside, 4.001)
In_vals
```

```{r}
par(pty = "s")
roc(true_split_I[[2]]$Signal, pred_test_I, 
    plot = TRUE, smoothed = TRUE, legacy.axes = TRUE, percent = TRUE, 
    xlab = "False Positive Rate (FPR)", ylab = "True Positive Rate (TPR)", col = "blue3",
    ci = TRUE, ci.alpha = 0.9, stratified = FALSE,
    auc = TRUE, grid=TRUE, print.auc=TRUE, print.auc.x = 70, print.auc.y = 55, show.thres=TRUE)

xgb.ggplot.importance(xgb.importance(model = tr_xgb_I), top_n = 10)
```

```{r}
var_I <- true_split_I[[2]] %>% mutate(Signal_pred = xgbpred_I) %>% select("MissingET.MET", "MissingET.Phi", "Lepton.PT", "Lepton.Phi", "ScalarHT.HT", "Jet1.PT", "BJet.PT", "Signal", "Signal_pred") %>% sample_n(NROW(true_split_I[[2]])/10)
var_I <- assign_label(var_I, 0.6)

col_I <- group_color(var_I)   
var_I[col_I[,1]!=col_I[,2],"Signal_pred"] <- if_else(col_I[col_I[,1]!=col_I[,2],1]=="black", 2, 3)  
# False positive = Green/2 and False negative = red/3 
write_csv(var_I, "/home/user1/Desktop/tourr variables/var_I.csv")

# Rescale
var_I <- rescale(var_I[,-8])

# Save tour history
t_I <- save_history(var_I[,-8], guided_tour(ashapetour(cl = col_I[,3], alpha = 0.4, hull_var = c("black")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(var_I[,-8], planned_tour(t_I), col = col_I[,3], fps = 50)
X11()

htmlwidgets::saveWidget(as_widget(create_animation(t_I, "/home/user1/Desktop/tourr variables/var_I.csv", var_I)), "/home/user1/Desktop/Images for thesis/tourr/plotly animation/bm_I.html")

# Save the tour plot
render(var_I[,-8], planned_tour(t_I), display_xy(col = col_I), frames = 50, "png", "/home/user1/Desktop/Images for thesis/tourr/bm_I/3//bm_I_3-%03d.png")
# pdf version actually captures the whole path
```

For the training set
```{r}
var_I_tr <- true_split_I[[1]] %>% select("MissingET.MET", "MissingET.Phi", "Lepton.PT", "Lepton.Phi", "ScalarHT.HT", "Jet1.PT", "BJet.PT", "Signal") %>% sample_n(NROW(true_split_I[[1]])/10)

col_v_I_tr <- if_else(var_I_tr$Signal==0, "black", "blue")
write_csv(as.data.frame(var_I_tr), "/home/user1/Desktop/tourr variables/var_I_tr.csv")
# Rescale
var_I_tr <- rescale(var_I_tr[,-8]) 

# Save tour history
t_I_tr <- save_history(var_I_tr, guided_tour(ashapetour(cl = col_v_I_tr, alpha = 0.4, hull_var = c("black")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(var_I_tr, planned_tour(t_I_tr), col = col_v_I_tr, fps = 50)
X11()

htmlwidgets::saveWidget(as_widget(create_animation_tr(t_I_tr, "/home/user1/Desktop/tourr variables/var_I_tr.csv", var_I_tr)), "/home/user1/Desktop/Images for thesis/tourr/plotly animation/bm_I_tr.html")

# Save the tour plot
render(var1_tr, planned_tour(t_I_tr), display_xy(col = col_v_I_tr), frames = 50, "png", "/home/user1/Desktop/Images for thesis/tourr/bm_I/bm_I_tr1-%03d.png")
# pdf version actually captures the whole path
```


Only the misclassified points
```{r}
false_I <- read_csv("/home/user1/Desktop/tourr variables/var_I.csv")
false_I <- subset(false_I, col_v_I[,1]!=col_v_I[,2])

col_f_I <- if_else(false_I$Signal_pred=="2", "red", "blue") # blue is FN, red is FP
write_csv(as.data.frame(false_I), "/home/user1/Desktop/tourr variables/false_I.csv")
false_I <- rescale(select(false_I, -"Signal"))

f_I <- save_history(false_I[,-ncol(false_I)], guided_tour(ashapetour(cl = col_f_I, alpha = 0.4, hull_var = c("red")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(false_I[,-ncol(false_I)], planned_tour(f_I), col = col_f_I, fps = 50)
X11()

animation_FPFN(f_I, "/home/user1/Desktop/tourr variables/false_I.csv", false_I)
```

Only for the signal points
```{r}
fntp_I <- read_csv("/home/user1/Desktop/tourr variables/var_I.csv")
fntp_I <- subset(fntp_I, fntp_I[,"Signal"]=="1")
write_csv(as.data.frame(fntp_I), "/home/user1/Desktop/tourr variables/fntp_I.csv")
col_sig_I <- if_else(fntp_I$Signal_pred=="3", "red", "blue") # blue is TP, red is FN
fntp_I <- rescale(select(fntp_I, -"Signal"))

sig_I <- save_history(fntp_I[,-ncol(fntp_I)], guided_tour(ashapetour(cl = col_sig_I, alpha = 0.4, hull_var = c("red")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(fntp_I[,-ncol(fntp_I)], planned_tour(sig_I), col = col_sig_I, fps = 50)
X11()

animation_signal(sig_I, "/home/user1/Desktop/tourr variables/fntp_I.csv", fntp_I)
```

Only for the background points
```{r}
fptn_I <- read_csv("/home/user1/Desktop/tourr variables/var_I.csv")
fptn_I <- subset(fptn_I, fptn_I[,"Signal"]=="0")
write_csv(as.data.frame(fptn_I), "/home/user1/Desktop/tourr variables/fptn_I.csv")
col_back_I <- if_else(fptn_I$Signal_pred=="2", "red", "blue") # blue is TN, red is FP
fptn_I <- rescale(select(fptn_I, -"Signal"))

back_I <- save_history(fptn_I[,-ncol(fptn_I)], guided_tour(ashapetour(cl = col_back_I, alpha = 0.4, hull_var = c("blue")), search_f = tourr:::search_better, alpha = pi/2, cooling = 0.5), step_size = Inf)

X11()
animate_xy(fptn_I[,-ncol(fptn_I)], planned_tour(back_I), col = col_back_I, fps = 50)
X11()

animation_background(back_I, "/home/user1/Desktop/tourr variables/fptn_I.csv", fptn_I)
```

Create a gif
```{r}
all_dir <- list.dirs(path = "/home/user1/Desktop/Images for thesis/tourr/bm1/test", recursive = TRUE)
# change end of file according to the folder I want to create gifs with
for (d in all_dir){
  name <- paste0("/home/user1/Desktop/Images for thesis/tourr", "/bm1_test.gif") # change pasted name to match the run number
  fls <- list.files(d, full.names = TRUE)
  gifski(fls , name, loop = FALSE)
}
```
